steps:
# 1. Construir a imagem Docker
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile', '-t', 'gcr.io/ventros-gcp/health-pg', '.']

# 2. Enviar a imagem para o Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ventros-gcp/health-pg']

# 3. Implantar no Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: [
    'run', 'deploy', 'flask-health-pg',
    '--image', 'gcr.io/ventros-gcp/health-pg',
    '--platform', 'managed',
    '--region', 'southamerica-east1',
    '--allow-unauthenticated',
    '--set-cloudsql-instances=ventros-gcp:southamerica-east1:pg-prod',
    '--set-secrets', 'DB_CREDENTIALS=CREDENTIALS_FLASK_HEALTH_CHECK_PG_SQL_PROD:latest',
    '--set-env-vars', 'ENV=test',
    '--execution-environment=gen1',
    '--concurrency=90',
    '--max-instances=50',
    '--memory=512MBi',
    '--cpu=1',
    '--timeout=3600',
    '--port=3080'
        ]
